int  configlauncherbutton1callback(int butno,int i,void *Tmp) ;
void  configlauncherbutton1init(DIN *B,void *pt) ;
int  configlauncherbrowser1callback(int item,int i,void *Tmp) ;
int  configlaunchertextbox1callback(int cellno,int i,void *Tmp);
int  configlaunchersplbutton1callback(int butno,int i,void *Tmp) ;
void  configlaunchersplbutton1init(DIL *B,void *pt) ;
int  configlauncherbutton2callback(int butno,int i,void *Tmp) ;
void  configlauncherbutton2init(DIN *B,void *pt) ;
int  configlauncherbrowser2callback(int item,int i,void *Tmp) ;
void  configlauncherbrowser2init(DIRA *R,void *pt) ;
int  configlauncherfslide1callback(double val,int i,void *Tmp) ;
int  configlauncherbrowser3callback(int item,int i,void *Tmp) ;
void  configlauncherbrowser3init(DIRA *R,void *pt) ;
int  configlauncherbutton3callback(int butno,int i,void *Tmp) ;
void  configlauncherbutton3init(DIN *B,void *pt) ;
int configlauncherinit(void *Tmp) ;
int configlaunchercleanup(void *Tmp) ;
int configlauncherCallBack(void *Tmp,void *tmp) ;
int configlauncherResizeCallBack(void *Tmp) ;
int configlauncherWaitCallBack(void *Tmp) ;
